
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MRX
 */
public class Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Pelanggan
     */
    public Connection conn;
    public Statement cn;
    public Pelanggan() {
        initComponents();
        bersih();
        tampildata();
    }
    
    public void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/listrikdb","root","");
            cn=conn.createStatement();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"koneksi gagal");
           System.out.println(e.getMessage());
        }
        
    }
    
    public void bersih(){
       id_pel.setText("");
       nama_pel.setText("");
       alamat_pel.setText("");
    }
    
    public void tampildata(){
        DefaultTableModel tablenya = new DefaultTableModel();
        tablenya.addColumn("id_pel");
        tablenya.addColumn("nama");
        tablenya.addColumn("alamat");
        try{
            koneksi();
            String sql = "Select*from pelanggantb";
            ResultSet rs =cn.executeQuery(sql);
            while (rs.next())
            {
                tablenya.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }jTable1.setModel(tablenya);
            
            }
            catch(Exception e){
           JOptionPane.showMessageDialog(null," anda salah");
                
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_pel = new javax.swing.JTextField();
        nama_pel = new javax.swing.JTextField();
        alamat_pel = new javax.swing.JTextField();
        btInput = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID Pelanggan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 110, 82, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 50, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 50, 14);
        getContentPane().add(id_pel);
        id_pel.setBounds(180, 100, 150, 30);
        getContentPane().add(nama_pel);
        nama_pel.setBounds(180, 140, 150, 30);
        getContentPane().add(alamat_pel);
        alamat_pel.setBounds(180, 180, 150, 30);

        btInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btInput.setText("Simpan");
        btInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputActionPerformed(evt);
            }
        });
        getContentPane().add(btInput);
        btInput.setBounds(360, 100, 100, 30);

        btHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btHapus);
        btHapus.setBounds(360, 140, 100, 30);

        btExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExit.setText("Keluar");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit);
        btExit.setBounds(360, 180, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 220, 400, 85);

        jLabel9.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel9.setText("Pelanggan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 20, 140, 32);

        setSize(new java.awt.Dimension(559, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql ="insert into pelanggantb values('"+id_pel.getText()+"',"
                    + "'"+nama_pel.getText()+"','"+alamat_pel.getText()+"')";
            cn.executeUpdate(sql);
            conn.close();

            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null, "berhasilll");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "koneksi ne gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btInputActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql ="delete from pelanggantb where id_pel =('"+id_pel.getText()+"')";
            cn.executeUpdate(sql);
            conn.close();

            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null, "berhasilll");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "koneksi gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris !=1) {
            id_pel.setText(jTable1.getValueAt(baris, 0).toString());
            nama_pel.setText(jTable1.getValueAt(baris, 1).toString());
            alamat_pel.setText(jTable1.getValueAt(baris, 2).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_pel;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btInput;
    private javax.swing.JTextField id_pel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_pel;
    // End of variables declaration//GEN-END:variables
}
